```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
library(scales)
library(ggcorrplot)

```

```{r Type 1 of 6 Agency Code Key}

agency_key_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/awards/count")

agency_key_parsed <- jsonlite::fromJSON(rawToChar(agency_key_raw$content))

agency_key_df <- as_tibble(agency_key_parsed$results[[1]]) |>
  rename("agency_name" = awarding_toptier_agency_name,
         "agency_code" = awarding_toptier_agency_code)

agency_key_df$agency_code <- as.numeric(agency_key_df$agency_code)

agency_key <- agency_key_df

agency_key

agency_key_plot <- ggplot(agency_key, aes(x = agency_name, y = contracts, fill = agency_name))

agency_key_plot +
  geom_col() +
  scale_fill_discrete(name = "Agency") +
  theme(axis.text.x = element_blank()) +  
  labs(x = "Agency", y = "# of Awards Granted") +
  coord_cartesian(ylim = c(0, 2000000))
  

```


```{r Data type 2 of 6 Agency Budget and Obligations}

agency_budget_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/012/budgetary_resources/")

agency_budget_parsed <- jsonlite::fromJSON(rawToChar(agency_budget_raw$content))

agency_budget_df <- as_tibble(agency_budget_parsed$agency_data_by_year) |>
  select(fiscal_year:total_budgetary_resources) |>
  rename("agency_budget" = agency_budgetary_resources,
         "agency_obligations" = agency_total_obligated) |>
  mutate("agency_code" = 12, .before = fiscal_year)

agency_budget <- agency_key |>
  select(agency_name, agency_code) |>
  right_join(agency_budget_df, join_by(agency_code)) 

             
agency_budget 

agency_budget_plot <- ggplot(agency_budget, aes(x = fiscal_year, y = agency_budget))

agency_budget_plot +
  geom_line(aes(y = agency_budget, color = "Budget")) +
  geom_line(aes(y = agency_obligations, color = "Obligations")) +
  scale_y_continuous(labels=dollar) +
  scale_color_manual("$ Amount Type", 
                     breaks = c("Budget", "Obligations"), 
                     values = c("blue", "red")) +
  labs(title = "Agency Budget", x = "Budget Year", y = "$ Amount") 

```


```{r data type 3 of 6 Agency Obligations}

agency_account_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/012/federal_account/")

agency_account_parsed <- jsonlite::fromJSON(rawToChar(agency_account_raw$content))

agency_account_df <- as_tibble(agency_account_parsed$results) |>
  select(code, name, obligated_amount, gross_outlay_amount) |>
  mutate("agency_code" = 12, .before = code)

agency_account <- agency_key |>
  select(agency_name, agency_code) |>
  right_join(agency_account_df, join_by(agency_code))

agency_account

agency_account_plot <- ggplot(agency_account, aes(code, obligated_amount, fill = code))

agency_account_plot +
  geom_col() +
  scale_y_continuous(label = dollar)+
  theme(axis.text.x = element_blank()) +
  scale_fill_discrete(name = "Program Code")+
  labs(x = "Program Code", y = "$ Amount")

```


```{r Data type 4 of 6 Agency Obligation Class}

agency_object_class_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/012/object_class")

agency_object_class_parsed <- jsonlite::fromJSON(rawToChar(agency_object_class_raw$content))

agency_object_class_df <- as_tibble(agency_object_class_parsed$results) |>
  rename("obligation_name" = name) |>
  mutate("agency_code" = 12, .before = obligation_name)

agency_object <- agency_key |>
  select(agency_name, agency_code) |>
  right_join(agency_object_class_df, join_by(agency_code))

agency_object



agency_object_plot <- ggplot(agency_object, aes(obligation_name, obligated_amount, color = obligation_name))

agency_object_plot +
  geom_point(aes(gross_outlay_amount, shape = "Object")) +
  geom_point(aes(obligated_amount, shape = "Obligated")) +
  scale_y_continuous(labels=dollar) +
  scale_color_discrete(name = "Obligation Type") +
  scale_shape_discrete(name = "Shape") +
  theme(axis.text.x = element_blank()) +
  labs(x = "Obligation", y = "$ Amount Spent") +
  coord_cartesian(ylim = c(0,110000000000))


```


```{r Data type 5 of 6 Agency Award Types}


agency_obligations_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/012/obligations_by_award_category")

agency_obligations_parsed <- jsonlite::fromJSON(rawToChar(agency_obligations_raw$content))

agency_obligations_df <- as_tibble(agency_obligations_parsed$results) |>
  mutate("agency_code" = 12, .before = category)  


agency_obligations <- agency_key |>
  select(agency_name, agency_code) |>
  right_join(agency_obligations_df, join_by(agency_code))

agency_obligations

agency_obligations_plot <- ggplot(data = agency_obligations, aes(x = category, y = aggregated_amount, fill = category))

agency_obligations_plot +
  geom_col() +
  scale_y_continuous(labels = dollar)+
  scale_fill_discrete(name = "Obligation Award Type")+
  theme(axis.text.x = element_blank())


```


```{r Data type 6 of 6 Agency Activities}

agency_activities_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/012/program_activity/")

agency_activities_parsed <- jsonlite::fromJSON(rawToChar(agency_activities_raw$content))

agency_activities_df <- as_tibble(agency_activities_parsed$results) |>
  mutate("agency_code" = 12, .before = name)

agency_activities <- agency_key |>
  select(agency_name, agency_code) |>
  right_join(agency_activities_df, join_by(agency_code))

agency_activities

agency_activities_plot <- ggplot(data = agency_activities, aes(x = name, y = gross_outlay_amount))

agency_activities_plot +
  geom_point(aes(gross_outlay_amount, color = "Budgeted")) +
  geom_point(aes(obligated_amount, color = "Obligated")) +
  scale_y_continuous(labels = dollar)+
  scale_fill_discrete(name = "Program Activity")+
  labs(x = "Program Activity", y = "$ Amount Spent") +
  theme(axis.text.x = element_blank())+
  theme(strip.text = element_text(size = 6)) +
  scale_color_manual("", 
                   breaks = c("Budgeted", "Obligated"), 
                   values = c("blue", "red")) +
  facet_wrap(~name, labeller = labeller(name = label_wrap_gen(width = 15)))

```

```{r Data page code to generate inital data table and plot}
#  The first thing we're going to do is generate the key that ties
#  the agencies with the code that is used throughout the remaining
#  API endpoints. 
#  
#  The agency key also has a data table associated with it that we will 
#  use as a static display to drive the interest of the user to 
#  further investigate the separate departments.
#   
  
  agency_key_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/awards/count")

  agency_key_parsed <- jsonlite::fromJSON(rawToChar(agency_key_raw$content))

  agency_key_df <- as_tibble(agency_key_parsed$results[[1]]) |>
    rename("agency_name" = awarding_toptier_agency_name,
           "agency_code" = awarding_toptier_agency_code,
           "indef_deliv_contract" = idvs) |>
    mutate(total_awards = contracts + direct_payments + grants + indef_deliv_contract + loans + other) |>
    arrange(desc(total_awards))
  

  agency_key_df$agency_code <- as.numeric(agency_key_df$agency_code)

  agency_key <- agency_key_df

  agency_key
  
  agency_key_plot <- ggplot(agency_key, aes(x = agency_name, y = total_awards, fill = agency_name))

agency_key_plot +
  geom_col() +
  scale_fill_discrete(name = "Agency") +
  theme(axis.text.x = element_blank()) +  
  labs(x = "Agency", y = "# of Awards Granted")
  
  
#  Write the function to que agency and endpoints 


govt_spending <-function(agency_name = "Department of Defense", report = "Program Activity") {
  
#  First, we need to convert our agency name into it's associated code
#  for use in pulling the differing data sets at the endpoints. 


### vvv Troubleshooting: This conditional logic works in R, is not working using shinyDashboard vvv ###      
  if(agency_name %in% "Department of Defense") {
    agency_code = "097"
  } else if(agency_name %in% "Department of Agriculture") {
    agency_code = "012"
  } else if(agency_name %in% "General Services Administration") {
    agency_code = "047"
  } else if(agency_name %in% "Department of Housing and Urban Development") {
    agency_code = "086"
  } else if(agency_name %in% "Department of Veterans Affairs") {
    agency_code = "036"
  } else if(agency_name %in% "Social Security Administration") {
    agency_code = "028"
  } else if(agency_name %in% "Department of Health and Human Services") {
    agency_code = "075"
  } else if(agency_name %in% "Federal Communications Commission") {
    agency_code = "027"
  } else if(agency_name %in% "Small Business Administration") {
    agency_code = "073"
  } else if(agency_name %in% "Railroad Retirement Board") {
    agency_code = "060"
  } else {
    print ("Error: Incorrect Agency Selection")
    }
### ^^^ Troubleshooting: This conditional logic works in R, is not working using shinyDashboard ^^^ ###      
  
  
###  vvv  Troubleshooting: This conditional logic is working in R, outputs the final else   vvv  ###
###  vvv  "Error: Incorrect..." message instead of assigning an agency code vvv             vvv  ###      
#  if_else(agency_name %in% "Department of Defense", agency_code <- "097",
#    if_else(agency_name %in% "Department of Agriculture", agency_code <- "012",
#      if_else(agency_name %in% "General Services Administration", agency_code <- "047",
#        if_else(agency_name %in% "Department of Housing and Urban Development", agency_code <- "086",
#          if_else(agency_name %in% "Department of Veterans Affairs", agency_code <- "036", 
#            if_else(agency_name %in% "Social Security Administration", agency_code <- "028",
#              if_else(agency_name %in% "Department of Health and Human Services", agency_code <- "075",
#                if_else(agency_name %in% "Federal Communications Commission", agency_code <- "027", 
#                  if_else(agency_name %in% "Small Business Administration", agency_code <- "073", 
#                    if_else(agency_name %in% "Railroad Retirement Board", agency_code <- "060", print ("Error: Incorrect Agency #Selection")
#                      ))))))))))
###  ^^^  Troubleshooting: This conditional logic is working in R, outputs the final else   ^^^  ###
###  ^^^  "Error: Incorrect..." message instead of assigning an agency code vvv             ^^^  ###
  
  
#  Next we will generate conditional logic statements to determine the
#  endpoint information that will be generated. 
  
###  vvv  Troubleshooting: This conditional logic works in R, is not working using shinyDashboard  vvv  ###      
    if(report %in% "Budgetary Resources") {
    endpoint <- c("budgetary_resources")
    } else if(report %in% "Federal Account") {
      endpoint <- c("federal_account")
    } else if(report %in% "Obligation Type") {
      endpoint <- c("object_class")
    } else if(report %in% "Award Obligations") {
      endpoint <- c("obligations_by_award_category")
    } else if(report %in% "Program Activity") {
      endpoint <- c("program_activity")
    } else {
      print ("Error: Incorrect Report Selection")
      }
###  ^^^  Troubleshooting: This conditional logic works in R, is not working using shinyDashboard  ^^^  ###      

###  vvv  Troubleshooting: This conditional logic is working in R, outputs the final else   vvv  ###
###  vvv  "Error: Incorrect..." message instead of assigning an agency code vvv             vvv  ### 
#    if_else(report %in% "Budgetary Resources", endpoint <- "budgetary_resources", 
#      if_else(report %in% "Federal Account", endpoint <- "federal_account", 
#        if_else(report %in% "Obligation Type", endpoint <- "object_class", 
#          if_else(report %in% "Award Obligations", endpoint <- "obligations_by_award_category", 
#            if_else(report %in% "Program Activity", endpoint <- "program_activity", print ("Error: Incorrect Report Selection"))
#        ))))
###  ^^^  Troubleshooting: This conditional logic is working in R, outputs the final else   ^^^  ###
###  ^^^  "Error: Incorrect..." message instead of assigning an agency code vvv             ^^^  ### 
  
  
#  Now that we have the conditional logic statements generated, we
#  will use them to generate the API URLs and parse the API data 
#  we are going to use to generate our data tables and graphics.
  
  
  url_raw_data <- httr::GET(str_c("https://api.usaspending.gov/api/v2/agency/",agency_code, "/", endpoint, "/"))
  
  url_parsed <- jsonlite::fromJSON(rawToChar(url_raw_data$content))
  
  
  
#  Because each endpoint has different variables associated with it,
#  we will be using more conditional logic to extract usable data and
#  generate our summary graphics.
#  
#  Each data set had the agency code added to it for merging with the
#  agency name. This is necessary for the `full_join` that will be 
#  used to compare the different agencies with one another on the
#  `Data Exploration` tab of the app. 
#
#  There are 6 endpoints in all that will be analyzed. We will be 
#  using a `right_join` for each data set to merge the 

  
#  The first data table we're going to read in is
  if(endpoint %in% "budgetary_resources") {
    df <- as_tibble(url_parsed$agency_data_by_year) |>
      dplyr::select(fiscal_year:total_budgetary_resources) |>
      rename("agency_budget" = agency_budgetary_resources,
             "agency_obligations" = agency_total_obligated) |>
      mutate("agency_code" = agency_code, .before = 1)
  
    df$agency_code <- as.numeric(df$agency_code)
  
    endpoint_df <- agency_key |>
    dplyr::select(agency_name, agency_code) |>
    right_join(df, join_by(agency_code))  
  
    print(endpoint_df)
    
    endpoint_df_plot <- ggplot(endpoint_df, aes(x = fiscal_year, y = agency_budget))

    endpoint_df_plot +
      geom_line(aes(y = agency_budget, color = "Budget")) +
      geom_line(aes(y = agency_obligations, color = "Obligations")) +
      scale_y_continuous(labels=dollar) +
      scale_color_manual("$ Amount Type", 
                         breaks = c("Budget", "Obligations"), 
                     values = c("blue", "red")) +
      labs(title = "Agency Budget", x = "Budget Year", y = "$ Amount") 
    
    
  } else if(endpoint %in% "federal_account") {
      df <- as_tibble(url_parsed$results) |>
        dplyr::select(code, name, obligated_amount, gross_outlay_amount) |>
        mutate("agency_code" = agency_code, .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)

      endpoint_df <- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
  
      print(endpoint_df)
      
      endpoint_df_plot <- ggplot(endpoint_df, aes(code, obligated_amount, fill = code))

      endpoint_df_plot +
        geom_col() +
        scale_y_continuous(label = dollar)+
        theme(axis.text.x = element_blank()) +
        scale_fill_discrete(name = "Program Code")+
        labs(x = "Program Code", y = "$ Amount")
      
  } else if(endpoint %in% "object_class") {
      df <- as_tibble(url_parsed$results) |>
        rename("obligation_name" = name) |>
        mutate("agency_code" = agency_code, .before = 1)
      
        df$agency_code <- as.numeric(df$agency_code)


      endpoint_df <- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
  
      print(endpoint_df)
      
      
      endpoint_df_plot <- ggplot(endpoint_df, aes(obligation_name, obligated_amount, color = obligation_name))

      endpoint_df_plot +
        geom_point(aes(gross_outlay_amount, shape = "Object")) +
        geom_point(aes(obligated_amount, shape = "Obligated")) +
        scale_x_continuous() +
        scale_y_continuous(labels=dollar) +
        scale_color_discrete(name = "Obligation Type") +
        scale_shape_discrete(name = "Shape") +
        theme(axis.text.x = element_blank()) +
        labs(x = "Obligation", y = "$ Amount Spent") +
        coord_cartesian(ylim = c(0,120000000000))
      
  } else if(endpoint %in% "obligations_by_award_category") {
      df <- as_tibble(url_parsed$results) |>
        mutate("agency_code" = agency_code, .before = 1)  
      
      df$agency_code <- as.numeric(df$agency_code)      

      endpoint_df <- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
  
      print(endpoint_df)
      
      endpoint_df_plot <- ggplot(data = endpoint_df, aes(x = category, y = aggregated_amount, fill = category))

      endpoint_df_plot +
        geom_col() +
        scale_y_continuous(labels = dollar)+
        scale_fill_discrete(name = "Obligation Award Type")+
        theme(axis.text.x = element_blank()) +
        coord_cartesian(ylim = c(0,120000000000))
      
  } else if(endpoint %in% "program_activity") {
      no_na <- c("Undisclosed") 
      
      df <- as_tibble(url_parsed$results) |>
        mutate("agency_code" = agency_code, .before = 1) |>
        mutate(name = str_replace(name, "N/A", "UNDISCLOSED"))        

      df$agency_code <- as.numeric(df$agency_code)      

      
      
      endpoint_df <- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
  
      print(endpoint_df)
      
      endpoint_df_plot <- ggplot(data = endpoint_df, aes(x = name, y = gross_outlay_amount))

      endpoint_df_plot +
        geom_point(aes(gross_outlay_amount, color = "Budgeted")) +
        geom_point(aes(obligated_amount, color = "Obligated")) +
        scale_y_continuous(labels = dollar)+
        scale_fill_discrete(name = "Program Activity")+
        labs(x = "Program Activity", y = "$ Amount Spent") +
        theme(axis.text.x = element_blank())+
        theme(strip.text = element_text(size = 6)) +
        scale_color_manual("", 
                         breaks = c("Budgeted", "Obligated"), 
                         values = c("blue", "red")) +
        facet_wrap(~name, labeller = labeller(name = label_wrap_gen(width = 15)))
      
  } 
  
  }
  

#test the function

govt_spending()

```

```{r Genrate code for the Exploration tab}

  agency_key_raw <- httr::GET("https://api.usaspending.gov/api/v2/agency/awards/count")

  agency_key_parsed <- jsonlite::fromJSON(rawToChar(agency_key_raw$content))

  agency_key_df <- as_tibble(agency_key_parsed$results[[1]]) |>
    rename("agency_name" = awarding_toptier_agency_name,
           "agency_code" = awarding_toptier_agency_code,
           "indef_deliv_contract" = idvs) |>
    mutate(total_awards = contracts + direct_payments + grants + indef_deliv_contract + loans + other) |>
    arrange(desc(total_awards))
  

  agency_key_df$agency_code <- as.numeric(agency_key_df$agency_code)

  agency_key <- agency_key_df

  agency_key

report <- "Award Obligations"

    if(report %in% "Budgetary Resources") {
    endpoint <- c("budgetary_resources")
    } else if(report %in% "Federal Account") {
      endpoint <- c("federal_account")
    } else if(report %in% "Obligation Type") {
      endpoint <- c("object_class")
    } else if(report %in% "Award Obligations") {
      endpoint <- c("obligations_by_award_category")
    } else if(report %in% "Program Activity") {
      endpoint <- c("program_activity")
    } else {
      print ("Error: Incorrect Report Selection")
      }

# Generate raw data for the reports for each of the departments
dod_url_raw_data <- httr::GET(str_c("https://api.usaspending.gov/api/v2/agency/097/", endpoint, "/"))
doa_url_raw_data <- httr::GET(str_c("https://api.usaspending.gov/api/v2/agency/012/", endpoint, "/"))
gsa_url_raw_data <- httr::GET(str_c("https://api.usaspending.gov/api/v2/agency/047/", endpoint, "/"))


# Parse the raw data for the reports for each of the departments
dod_url_parsed <- jsonlite::fromJSON(rawToChar(dod_url_raw_data$content))
doa_url_parsed <- jsonlite::fromJSON(rawToChar(doa_url_raw_data$content))
gsa_url_parsed <- jsonlite::fromJSON(rawToChar(gsa_url_raw_data$content))


#convert data to tibble frames and merge them for generating reports
if(endpoint %in% "program_activity") {
      df <- as_tibble(dod_url_parsed$results) |>
        mutate("agency_code" = "097", .before = 1) |>
        mutate(name = str_replace(name, "N/A", "UNDISCLOSED"))        

      df$agency_code <- as.numeric(df$agency_code)      
      
      dod_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      dod_df
      
      df <- as_tibble(doa_url_parsed$results) |>
        mutate("agency_code" = "012", .before = 1) |>
        mutate(name = str_replace(name, "N/A", "UNDISCLOSED"))        

      df$agency_code <- as.numeric(df$agency_code)      
      
      doa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      doa_df
      
      df <- as_tibble(gsa_url_parsed$results) |>
        mutate("agency_code" = "047", .before = 1) |>
        mutate(name = str_replace(name, "N/A", "UNDISCLOSED"))        

      df$agency_code <- as.numeric(df$agency_code)      
      
      gsa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      gsa_df
      
      combined_1 <- dod_df |>
        full_join(doa_df)
      
      combined_df <- combined_1 |>
        full_join(gsa_df)
      
      print(combined_df)
      
      combined_df_facet <- ggplot(data = combined_df, aes(x = name, y = gross_outlay_amount))

      combined_facet_plot <- combined_df_facet +
        geom_point(aes(gross_outlay_amount, color = "Budgeted")) +
        geom_point(aes(obligated_amount, color = "Obligated")) +
        scale_y_continuous(labels = dollar)+
        scale_fill_discrete(name = "Program Activity")+
        labs(x = "Program", y = "$ Amount Spent") +
        theme(axis.text.x = element_blank())+
        theme(strip.text = element_text(size = 4)) +
        scale_color_manual("", 
                         breaks = c("Budgeted", "Obligated"), 
                         values = c("blue", "red")) +
        facet_wrap(~name, labeller = labeller(name = label_wrap_gen(width = 15)))
      
      print(combined_facet_plot)
      
      combined_df_point <- ggplot(data = combined_df, aes(x = name, y = gross_outlay_amount, shape = agency_name))
      
      combined_point_plot <- combined_df_point +
        geom_point() +
        scale_shape_discrete(name = "Agency") +
        scale_y_continuous(labels=dollar) +
        theme(axis.text.x = element_blank()) +  
        labs(x = "Program", y = "$ Spent on Program") +
        coord_cartesian(ylim = c(0, 175000000000))
        
      print(combined_point_plot)

} else if(endpoint %in% "budgetary_resources") {
      df <- as_tibble(dod_url_parsed$agency_data_by_year) |>
        dplyr::select(fiscal_year:total_budgetary_resources) |>
        rename("agency_budget" = agency_budgetary_resources,
             "agency_obligations" = agency_total_obligated) |>
        mutate("agency_code" = "097", .before = 1)       

      df$agency_code <- as.numeric(df$agency_code)      
      
      dod_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      dod_df
      
      df <- as_tibble(doa_url_parsed$agency_data_by_year) |>
        dplyr::select(fiscal_year:total_budgetary_resources) |>
        rename("agency_budget" = agency_budgetary_resources,
             "agency_obligations" = agency_total_obligated) |>
        mutate("agency_code" = "012", .before = 1)  
      
      df$agency_code <- as.numeric(df$agency_code)      
      
      doa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      doa_df
      
      df <- as_tibble(gsa_url_parsed$agency_data_by_year) |>
        dplyr::select(fiscal_year:total_budgetary_resources) |>
        rename("agency_budget" = agency_budgetary_resources,
             "agency_obligations" = agency_total_obligated) |>
        mutate("agency_code" = "047", .before = 1)  
      
      df$agency_code <- as.numeric(df$agency_code)      
      
      gsa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      gsa_df
      
      combined_1 <- dod_df |>
        full_join(doa_df)
      
      combined_df <- combined_1 |>
        full_join(gsa_df)
      
      print(combined_df)
      
      combined_df_point <- ggplot(data = combined_df, aes(x = fiscal_year, y = agency_budget, color = agency_name))
      
      combined_point_plot <- combined_df_point +
        geom_point(aes(y = agency_budget, shape = "Budget")) +
        geom_point(aes(y = agency_obligations, shape = "Obligations")) +
        scale_color_discrete(name = "Agency") +
        scale_shape_discrete(name = "Budget / Obligation") +
        scale_y_continuous(labels=dollar) +
        labs(x = "Fiscal Year", y = "$ Spent by Agency") 
      
      print(combined_point_plot)
      
      combined_df_box <- ggplot(data = combined_df, aes(x = fiscal_year, y = agency_budget))
      
      combined_box_plot <- combined_df_box +
        geom_boxplot(aes(group = fiscal_year, fill = "red")) +
        scale_y_continuous(name="$ Spent per Year", label=dollar) +
        scale_x_continuous(name="Budget Year") +
        guides(fill = FALSE) 

      print(combined_box_plot)
} else if(endpoint %in% "federal_account") {
      df <- as_tibble(dod_url_parsed$results) |>
        dplyr::select(code, name, obligated_amount, gross_outlay_amount) |>
        mutate("agency_code" = "097", .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)      
      
      dod_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      dod_df
      
      df <- as_tibble(doa_url_parsed$results) |>
        dplyr::select(code, name, obligated_amount, gross_outlay_amount) |>
        mutate("agency_code" = "012", .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)      
      
      doa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      doa_df
      
      df <- as_tibble(gsa_url_parsed$results) |>
        dplyr::select(code, name, obligated_amount, gross_outlay_amount) |>
        mutate("agency_code" = "047", .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)      
      
      gsa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))  
      
      gsa_df
      
      combined_1 <- dod_df |>
        full_join(doa_df)
      
      combined_df <- combined_1 |>
        full_join(gsa_df)
      
      print(combined_df)
      
      combined_df_col <- ggplot(combined_df, aes(x=name, y=obligated_amount, fill = code))
      
      combined_col_plot <- combined_df_col +
        geom_col() +
        theme(axis.text.x = element_blank()) +
        scale_y_continuous(labels=dollar) +
        scale_fill_discrete(name="Program Code") +
        labs(x="Program", y="$ Amount Obligated")
        
      print(combined_col_plot)
      
      combined_df_plot <- (ggplot(combined_df, aes(shape=agency_name))) #, aes(x=obligated_amount, y=agency_name)))
      
      combined_qq_plot <- combined_df_plot +
        geom_qq(aes(sample=obligated_amount)) +
        geom_qq(aes(sample=gross_outlay_amount)) +
        scale_y_continuous(labels=dollar) +
        scale_shape_discrete(name="Agency") +
        labs(x="Theoretical Data", y="$ Amount Spent")
      
      print(combined_qq_plot)
      
} else if(endpoint %in% "object_class") {
      df <- as_tibble(dod_url_parsed$results) |>
        rename("obligation_name" = name) |>
        mutate("agency_code" = "097", .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)
      
      dod_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code)) 
      
      dod_df
      
      df <- as_tibble(doa_url_parsed$results) |>
        rename("obligation_name" = name) |>
        mutate("agency_code" = "012", .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)
      
      doa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))
      
      doa_df
      
      df <- as_tibble(gsa_url_parsed$results) |>
        rename("obligation_name" = name) |>
        mutate("agency_code" = "047", .before = 1)
      
      df$agency_code <- as.numeric(df$agency_code)
      
      gsa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code))
      
      gsa_df
      
      combined_1 <- dod_df |>
        full_join(doa_df)
      
      combined_df <- combined_1 |>
        full_join(gsa_df)
      
      print(combined_df)
      
      combined_df_tile <- ggplot(combined_df, aes(x=agency_name, y=obligation_name, fill=obligated_amount))
      
      combined_tile_plot <- combined_df_tile +
        geom_tile() +
        labs(x="Agency", y="Award Obligation", fill="$ Obligated") +
        theme(axis.text.x = element_blank()) 
      
      print(combined_tile_plot)
      
      combined_df_bar <- ggplot(combined_df, aes(x=obligation_name ))
      
      combined_bar_plot <- combined_df_bar +
        geom_bar(aes(fill=agency_name )) +
        scale_fill_discrete(name="Agency") +
        theme(axis.text.x = element_blank(),
              legend.position = "bottom",
              legend.text = element_text(size=8)) +        
        labs(title="Histogram of Agency Award Recepients by Type",
             x="Award Recepients",
             y="# of Agencies")
        
      print(combined_bar_plot)      

      
      
} else if(endpoint %in% "obligations_by_award_category") {
        df <- as_tibble(dod_url_parsed$results) |>
        mutate("agency_code" = "097", .before = 1)  

        df$agency_code <- as.numeric(df$agency_code)
      
        dod_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code)) 
      
        dod_df
      
        df <- as_tibble(doa_url_parsed$results) |>
        mutate("agency_code" = "012", .before = 1)  

        df$agency_code <- as.numeric(df$agency_code)
      
        doa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code)) 
      
        doa_df
      
        df <- as_tibble(gsa_url_parsed$results) |>
        mutate("agency_code" = "047", .before = 1)  
        
        df$agency_code <- as.numeric(df$agency_code)
      
        gsa_df <<- agency_key |>
        dplyr::select(agency_name, agency_code) |>
        right_join(df, join_by(agency_code)) 
      
        gsa_df
        
      combined_1 <- dod_df |>
        full_join(doa_df)
      
      combined_df <- combined_1 |>
        full_join(gsa_df)
      
      print(combined_df)
}
```



  



